name: deadwood_forecasting_model
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - affine=2.4.0=pyhd8ed1ab_1
  - aiobotocore=2.25.2=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py312h5d8c7f2_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aom=3.9.1=hac33072_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - backports.zstd=1.3.0=py312h90b7ffd_0
  - blas=1.0=mkl
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.8.1=pyhd8ed1ab_0
  - botocore=1.40.70=pyhd8ed1ab_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py312hdb49522_1
  - brunsli=0.1=hd1e3526_2
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - c-blosc2=2.22.0=hc31b594_1
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - captum=0.8.0=0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hd9148b4_3
  - cpython=3.12.12=py312hd8ed1ab_1
  - cuda-cudart=12.4.127=he02047a_2
  - cuda-cudart_linux-64=12.4.127=h85509e4_2
  - cuda-cupti=12.4.127=he02047a_2
  - cuda-libraries=12.4.1=ha770c72_1
  - cuda-nvrtc=12.4.127=he02047a_2
  - cuda-nvtx=12.4.127=he02047a_2
  - cuda-opencl=12.4.127=he02047a_1
  - cuda-runtime=12.4.1=ha804496_0
  - cuda-version=12.4=h3060b56_3
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py312h4c3975b_1
  - dask=2025.12.0=pyhcf101f3_0
  - dask-core=2025.12.0=pyhcf101f3_1
  - dav1d=1.2.1=hd590300_0
  - debugpy=1.8.19=py312h372c3de_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distributed=2025.12.0=pyhcf101f3_1
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - duckdb=1.4.3=h332efcf_0
  - executing=2.2.1=pyhd8ed1ab_0
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.61.1=py312h8a5da7c_0
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - frozenlist=1.7.0=py312h447239a_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - geopandas=1.1.2=pyhd8ed1ab_0
  - geopandas-base=1.1.2=pyha770c72_0
  - geos=3.14.1=h480dda7_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312hcaba1f9_2
  - google-crc32c=1.8.0=py312h03f33d3_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py312ha4f8f14_101
  - hdf5=1.14.6=nompi_h1b119a7_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2026.1.1=py312ha4965bc_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_2
  - krb5=1.21.3=h659f571_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.5=gpl_hc2c16d8_100
  - libarrow=22.0.0=hb6ed5f4_6_cpu
  - libarrow-acero=22.0.0=h635bf11_6_cpu
  - libarrow-compute=22.0.0=h8c2c5c3_6_cpu
  - libarrow-dataset=22.0.0=h635bf11_6_cpu
  - libarrow-substrait=22.0.0=h3f74fd7_6_cpu
  - libavif16=1.3.0=h316e467_3
  - libblas=3.9.0=20_linux64_mkl
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.9.0=20_linux64_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.4.5.8=he02047a_2
  - libcufft=11.2.1.3=he02047a_2
  - libcufile=1.9.1.3=he02047a_2
  - libcurand=10.3.5.147=he02047a_2
  - libcurl=8.18.0=h4e3cde8_0
  - libcusolver=11.6.1.9=he02047a_2
  - libcusparse=12.3.1.170=he02047a_2
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgdal-core=3.12.1=hf05ffb4_0
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.9.0=20_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=12.2.5.30=he02047a_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.4.127=he02047a_2
  - libnvjitlink=12.4.127=he02047a_2
  - libnvjpeg=12.3.1.117=he02047a_2
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=22.0.0=h7376487_6_cpu
  - libpng=1.6.53=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - librttopo=1.1.0=h46dd2a8_20
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.2=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py312h3d67a73_1
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - matplotlib-base=3.10.8=py312he3d6523_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - minizip=4.0.10=h05a5f5f_0
  - mkl=2023.2.0=ha770c72_50498
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py312hd9148b4_1
  - multidict=6.7.0=py312h8a5da7c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h5888daf_0
  - narwhals=2.15.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nodejs=18.20.5=hc38da69_2
  - numcodecs=0.16.5=py312hf79963d_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.26.0=h8d634f6_0
  - openssl=3.6.1=h35e630c_1
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - proj=9.7.1=h99ae125_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h178313f_0
  - psutil=7.2.1=py312h5253ce2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py312h7900ff3_0
  - pyarrow-core=22.0.0=py312hc195796_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.12.1=py312h053e1f3_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyproj=3.7.2=py312h9b6a7d9_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-duckdb=1.4.3=py312h1289d80_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-lmdb=1.7.5=py312h8285ef7_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytorch=2.5.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qhull=2020.2=h434a139_5
  - rasterio=1.5.0=py312hcedc861_0
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - rioxarray=0.20.0=pyhd8ed1ab_0
  - s2n=1.6.2=he8a4886_1
  - s3fs=2025.12.0=pyhd8ed1ab_0
  - scikit-image=0.26.0=np2py312h4ae17e4_0
  - scikit-learn=1.8.0=np2py312h3226591_1
  - scipy=1.16.3=py312h54fa4ab_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py312h383787d_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.51.2=hbc0de68_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py312h4f23490_0
  - svt-av1=4.0.0=hecca717_0
  - tbb=2021.13.0=hb700be7_5
  - tblib=3.2.2=pyhcf101f3_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2026.1.14=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - toolz=1.1.0=pyhd8ed1ab_1
  - torchtriton=3.1.0=py312
  - tornado=6.5.4=py312h961da02_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py312h4c3975b_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py312h4c3975b_1
  - xarray=2025.12.0=pyhcf101f3_0
  - xerces-c=3.3.0=h988505b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py312h8a5da7c_0
  - zarr=3.1.5=pyhcf101f3_0
  - zeromq=4.3.5=h387f397_9
  - zfp=1.0.1=h909a3a2_5
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstandard=0.25.0=py312h5253ce2_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - filelock==3.20.0
      - markupsafe==2.1.5
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - pillow==12.0.0
      - sympy==1.13.1
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - triton==3.2.0
prefix: /home/mp426/miniconda3/envs/S3
